### ISSUE TITLE
NPM install broken

### ISSUE THREAD

**Issue by HariSekhon** [so-fancy/diff-so-fancy#350]
I've tested this on both CentOS and Ubuntu on docker and found it broken in both cases, looks like an NPM installation issue:

```
# npm install diff-so-fancy
/
`-- diff-so-fancy@1.2.7 

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
```

**Comment by stevemao** [comment]
I just tried `npm install diff-so-fancy`, it works fine for me.

**Comment by HariSekhon** [comment]
That's strange, I've reproduced this on CentOS and Ubuntu latest docker images and both had the same problem  - it looked like a package issue due to:
```
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
```

**Comment by HariSekhon** [comment]
I've just reproduced it again on both CentOS and Ubuntu latest docker images to double check:

CentOS:
```
docker run --rm -ti centos /bin/bash
yum install -y epel-release
yum install -y npm
npm install diff-so-fancy
```
gives
```
/
`-- diff-so-fancy@1.2.7

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
```

Ubuntu:
```
docker run --rm -ti ubuntu /bin/bash
apt-get update
apt-get install -y npm
npm install diff-so-fancy
```
gives the same.

**Comment by scottchiefbaker** [comment]
Where are we at on this issue? I don't publish to NPM, so I'm not sure who to contact.

**Comment by jfcherng** [comment]
@stevemao Could you help update the [npm package](https://www.npmjs.com/package/diff-so-fancy). Thanks. (I see you are one of the package collaborator)

**Comment by stevemao** [comment]
@jfcherng sorry for late response. I just published the latest to npm

**Comment by OJFord** [comment]
I'm not an npm user, but just had a look at this; it would still occur as given above regardless of published version, but that's because you're not installing 'globally', i.e. system-wide.

`npm install diff-so-fancy` assumes you're trying to install to a local project, so it _warns_ (it's not 'broken' even then - the following stdout that's omitted above is still 'added 1 package from 1 contributor in 0.099s') that it can't find a `package.json` file to which to store your project's dependency on `diff-so-fancy`, that's all.

`npm install -g diff-so-fancy` to install system-wide and not even attempt to write to a `package.json`.
