### ISSUE TITLE
Uninitialized value error

### ISSUE THREAD

**Issue by ocsw** [so-fancy/diff-so-fancy#411]
Since upgrading to 1.4.1 this morning, I can't run diff-so-fancy (or any git command that runs it).  I get the following error from Perl:

Use of uninitialized value in addition (+) at /usr/local/bin/diff-so-fancy line 942.

**Comment by scottchiefbaker** [comment]
Interesting... you must have some unique colors specified in your `.gitconfig`. What is the output of:

    git config --list | grep diff-highlight

**Comment by ocsw** [comment]
$ git config --list | grep diff-highlight
color.diff-highlight.oldnormal=brightred bold
color.diff-highlight.oldhighlight=brightred bold 52
color.diff-highlight.newnormal=brightgreen bold
color.diff-highlight.newhighlight=brightgreen bold 22

**Comment by scottchiefbaker** [comment]
Aha... the "bright" was throwing it off. I just landed ed6018dfb646493f424751c1b0a75bf1cd8f9635 which should fix this issue. Can you test it out?

**Comment by ocsw** [comment]
Well, it runs now.  But I'm pretty sure it changed the colors on the @ line.
@ setup.py:66 @ def install_requires():
everything after the second @ is ... purple on gold?  I think it was gold on black before

**Comment by ocsw** [comment]
I should mention I have these:

[diff-so-fancy]
	rulerwidth = 47
	useunicoderuler = false
	stripleadingsymbols = false
	markemptylines = false
[color "diff"]
	commit = brightyellow bold
	meta = brightcyan bold
	frag = brightmagenta bold
	func = brightmagenta bold
	old = brightred bold
	new = brightgreen bold
	whitespace = red reverse
[color "diff-highlight"]
	oldnormal = brightred bold
	oldhighlight = brightred bold 52
	newnormal = brightgreen bold
	newhighlight = brightgreen bold 22

**Comment by ocsw** [comment]
Also
[pretty]
	oneline-name = %C(yellow)%h%Cgreen%d %Creset%s%Cblue [%cn]
	oneline-name-nl = %n%C(yellow)%h%Cgreen%d %Creset%s%Cblue [%cn]
and
[core]
	pager = diff-so-fancy | less --tabs=4 -FRX
[interactive]
	difffilter = (echo && diff-so-fancy)

**Comment by scottchiefbaker** [comment]
There is a flaw in my color logic I will have to look at later. For now, try changing all your color words to numbers. The number logic should be fine, it's the mapping of English words to ANSI colors that's off.

**Comment by scottchiefbaker** [comment]
I dove in the [Git color documentation](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_colors_in_git) last night and I didn't find "brightred" as an option. It seemed simple enough so I think I found/fixed my bug. If you checkout the latest `next` branch the issue should be fixed.

**Comment by ocsw** [comment]
Interesting, I know I've seen docs with the bright prefix.  Might have been from another fancy diff.

**Comment by OJFord** [comment]
I found this, seems git does support 'bright<colour>' (no space) as ocsw's used here:
https://github.com/git/git/blob/142430338477d9d1bb25be66267225fb58498d92/t/t4026-color.sh#L33-L35

Note that depending on your terminal though, 'bright red' and 'red bold' may be the same; which would mean in a different terminal (or with proper bold support added) the colour of 'bright red' (and the colour _and_ weight of 'bright red bold') would change.

**Comment by OJFord** [comment]
Turns out I'm also hitting this, having accidentally only just upgraded to 1.4.1.. 👀 

For me, the troublesome line is:
```ini
[color "diff-hightlight"]
    newHighlight = 238 bold green
```

where `oldHighlight = red bold 52` is ok; `newHighlight = 238 bold` is ok; `newHighlight = green` is ok; `newHighlight = 238 green` is ok, but `238 green bold`, `238 bold green`, and `238 bold green bold` are _not_ ok.

I just mention that since my initial assumption was that I must have been using `bright` or similar too, but it turns out it can happen with just colours and bold too.

**Comment by scottchiefbaker** [comment]
Both `238 green bold` and `238 green bold` should work fine with the current code on `next`. Specifically they should map to: `\e[1;38;5;238;42m`, which I just confirmed. You can test the logic with `test/git_ansi_color.pl`

The last one will not work... we don't support four word color strings. You can only bold a string once. It may actually work, but I suspect the second bold is completely ignored. The way the logic works is to check for any bold or reverse strings, apply those at the beginning of the ANSI color sequence and then apply the fg and bg colors.

**Comment by solson** [comment]
`man git-config` documents the `brightred` option (emphasis mine):

> The basic colors accepted are normal, black, red, green, yellow, blue, magenta, cyan and white. The first color given is the foreground; the second is the background. **All the basic colors except normal have a bright variant that can be specified by prefixing the color with bright, like brightred.**

As for a temporary fix, I'm not sure what I'm doing wrong. My previous configuration `oldHighlight = brightred 52` would give me bright red foreground text (color code 9, if I understand correctly) and dark red background (52), but if I try to workaround with `oldHighlight = 9 52` I get only bright red foreground text, with a default non-red background.

**Comment by scottchiefbaker** [comment]
@solson are you saying your having color issues with the latest `next` branch? As far as I'm aware all the color issues have been addressed.

**Comment by solson** [comment]
@scottchiefbaker Ah, sorry, I thought it was unresolved. I tested on `v1.4.1` — I'll try now on `next`.

**Comment by scottchiefbaker** [comment]
There were a couple of corner cases, `brightred` being one of them, in v1.4.1. It should all be resolved in the `next` branch.

**Comment by solson** [comment]
Yep, it's all fixed on `next` as you said. Thanks!

**Comment by scottchiefbaker** [comment]
OK phew :)

**Comment by lugray** [comment]
I encountered this too. It's fixed on [next](https://github.com/so-fancy/diff-so-fancy/tree/next) for me too. When can we expect a v1.4.2?

**Comment by scottchiefbaker** [comment]
Ask and ye shall receive... I just released v1.4.2 which should address this issue.

**Comment by FatBoyXPC** [comment]
1.4.2 didn't seem to fix my issue:

`Use of uninitialized value in addition (+) at /usr/bin/diff-so-fancy line 967, <STDIN> line 25.`

Here are the colors from my git config if it helps:

```
[color]
    ui = true
[color "diff-highlight"]
    oldNormal = 196 bold
    oldHighlight = 196 bold 52
    newNormal = 34 bold
    newHighlight = 34 bold 22
[color "diff"]
    meta = 130
    frag = 33 bold dim
    commit = 172 bold
    old = 196 bold
    new = 34 bold
    whitespace = red reverse
```

**Comment by scottchiefbaker** [comment]
Thanks for providing the colors... that definitely helps.

My guess is that this bug is from your `frag` section which has the word dim in it. d-s-f doesn't (currently) support dim. If you just switch to to `33 bold` I bet this error goes away.

Also... do you want fragments to be bold, or dim? It can't be both :)

**Comment by FatBoyXPC** [comment]
I'm not sure what I want :rofl: I think I copied this from somebody else's config where they provided a screenshot, but it's been too long to tell!. 

That said, you were right, thanks!

**Comment by scottchiefbaker** [comment]
We purposely don't implement EVERY possible ANSI config, dim just happened to one I didn't bother to put the time towards.

Glad it's working for you.

**Comment by jarednorman** [comment]
Working around by not using it, but it's choking on my use of `ul` (underline), as well.
